### ISSUE TITLE
Undefined subroutine

### ISSUE THREAD

**Issue by jonasrog** [Libriotech/koha-illbackend-libris#100]
When im trying to run "sudo koha-shell -c "perl /usr/share/koha/lib/Koha/Illbackends/Libris/cron/get_data_from_libris.pl -mode outgoing -sigil sigilname" koha-utv" it fails with the following error message:
Undefined subroutine &Koha::Illbackends::Libris::Base::AddItem called at /usr/share/koha/lib/Koha/Illbackends/Libris/Base.pm line 924.

Im running Koha 20.05.04.000 with the latest version of Libris.

**Comment by MagnusEnger** [comment]
This should be fixed by pull request #99 from Andreas Jonsson. Could you please test?

**Comment by MagnusEnger** [comment]
I assume this was fixed.
