### ISSUE TITLE
Import problems (Broken FK constraint)

### ISSUE THREAD

**Issue by jonasrog** [Libriotech/koha-illbackend-libris#101]
Any idea why we start to get this problem when we're running get_data_from_libris.pl? 
We've never had this problem before, it started some days ago.

Use of uninitialized value in join or string at /usr/share/perl5/MARC/Field.pm line 696.
Use of uninitialized value in join or string at /usr/share/perl5/MARC/Field.pm line 696.
DBD::mysql::st execute failed: Cannot add or update a child row: a foreign key constraint fails (`koha_koha`.`biblio_metadata`, CONSTRAINT `record_metadata_fk_1` FOREIGN KEY (`biblionumber`) REFERENCES `biblio` (`biblionumber`) ON DELETE CASCADE ON UPDATE CASCADE) [for Statement "INSERT INTO `biblio_metadata` ( `format`, `marcflavour`, `metadata`) VALUES ( ?, ?, ? )"
Broken FK constraint

Some items will get imported but then on some items this error message occurs and the script crashes.

Koha version 18.11.16.000. Not the latest version of the Libris-module.

**Comment by MagnusEnger** [comment]
If you did not upgrade/change either Koha or the plugin it sounds like a data problem. Could you have a look in the logs and see if the MARC record looks ok? I recently saw a problem where MARC records (from another source than Libris) were not imported because they had a datafield with an empty tag, something like this:

```<datafield tag="" ind1=" " ind2=" ">
</datafield>```

**Comment by jonasrog** [comment]
I couldn't see any empty <datafield>-tag, however when we added the item manually it worked like a charm to run the script. So im not sure why this happened. So for now we have a workaround for the issue.

We're in the middle of an upgrade-project to Koha 20.05 with the latest version of the module, hopefully that will fix it. We do have some other problems regarding that tho (another issue i posted here some days ago).

Thanks for the reply!

**Comment by MagnusEnger** [comment]
Closing this since you found a workaround.
