### ISSUE TITLE
Do not double translate statuses

### ISSUE THREAD

**Issue by jonasrog** [Libriotech/koha-illbackend-libris#71]
After importing the data from Libris the requests wont show up under "ILL Requests". There seem to be a problem with "capabilities" that's in the embed value in the querystring. If i try to go to the api-URL where the jQuery script tries to get data from (/api/v1/illrequests?embed=metadata,patron,library,capabilities,comments) it responses with:
 {"errors":[{"message":"Internal server error.","path":"\/"}],"status":500}. 
If i remove "capabilities" from the querystring everything seems to work just fine.

The plack-error log also gives me this message:
[error] Can't use an undefined value as an ARRAY reference at /usr/share/koha/lib/Koha/Illrequest.pm line 389.

**Comment by MagnusEnger** [comment]
I think errors like that usually are the result of a status in the database that is not present in the status_graph (Koha::Illbackends::Libris::Base::status_graph()). Could you please do this and report on the output:

```
SELECT status, COUNT(*) FROM illrequests GROUP BY status;
```

**Comment by jonasrog** [comment]
When i ran the SQL-query i got this:
+--------+----------+
| status | COUNT(*) |
+--------+----------+
| NULL   |       18 |
+--------+----------+

**Comment by MagnusEnger** [comment]
Huh? Did you fetch data for Inlån or Utlån? Can you check the logs/output from the get_data_from_libris.pl script and see what statuses the requests are supposed to have?

**Comment by jonasrog** [comment]
Im running it for outgoing. When im running the script with debug enabled this is what it says:

DEBUG: status = Levererad
DEBUG: status = Läst
DEBUG: status = Reserverad
DEBUG: status = Negativt svar

But once it shows the $VAR1 array when its about to add a new request it looks like this:
$VAR1 = {
          'method' => 'create',
          'stage' => 'commit',
          'status' => '',
          'error' => 0,
          'permitted' => 1,
          'next' => 'illview',
          'message' => '',
          'opac_template' => '/usr/share/koha/lib/Koha/Illbackends/Libris/opac-includes/create.inc',
          'template' => '/usr/share/koha/lib/Koha/Illbackends/Libris/intra-includes/create.inc'
        };

So it seems to fail to even set the prefix in the if-then-else statement on line 146.

**Comment by MagnusEnger** [comment]
Hm, as you say it is totally weird that the prefix is not set! 

I did a really stupid commit a couple days ago:
https://github.com/Libriotech/koha-illbackend-libris/commit/d1d1a308b1de8c2fadd83a572de7c8d2d9c14d61

Maybe it is an unintended consequence of that. 

Could you try this:

```
git reset --hard HEAD^
``` 

a couple of times, until you are at "Make it possible to receive more statuses" and see if it works better then?

**Comment by MagnusEnger** [comment]
I reverted the stupid commit, so please just "git pull" and try running get_data_from_libris.pl and see if it works better now.

**Comment by jonasrog** [comment]
The result is still the same. Although i did some research now where i followed how the $status var was built from time to time. I put a print of the var just before it should proceed and insert it:

print "Status = $status\n";
my $backend_result = $illrequest->backend_create({

The output i had was:
Status = IN_LAST
$VAR1 = {
          'message' => '',
          'stage' => 'commit',
          'status' => '',
          'template' => '/usr/share/koha/lib/Koha/Illbackends/Libris/intra-includes/create.inc',
          'opac_template' => '/usr/share/koha/lib/Koha/Illbackends/Libris/opac-includes/create.inc',
          'next' => 'illview',
          'permitted' => 1,
          'error' => 0,
          'method' => 'create'
        };

So it seems like the backend_create ignores/removes that var for some reason.

Just in case there might be some configuration error i will post our settings below:
<interlibrary_loans>
  <branch>FJARRLAN</branch>
  <backend_directory>/usr/share/koha/lib/Koha/Illbackends</backend_directory>
  <libris_sigil>Mhs</libris_sigil>
  <libris_key>***</libris_key>
  <libris_borrowernumber>54942</libris_borrowernumber>
  <unknown_patron>55069</unknown_patron>
  <unknown_biblio>42635</unknown_biblio>
  <ill_branch>FJARRLAN</ill_branch>
  <ill_itemtype>FJARRLAN</ill_itemtype>
  <ill_closed_itemtype>FJARRLANX</ill_closed_itemtype>
 </interlibrary_loans>

**Comment by MagnusEnger** [comment]
Interesting! 

Which version of Koha are you on? I have been developing/testing on 18.11 and master.

**Comment by jonasrog** [comment]
Version info about the installation:
OS: Ubuntu 18.04
Koha: 18.11.03.000
Perl: 5.026001
SQL: mysql Ver 15.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by MagnusEnger** [comment]
I think I have been able to reproduce this on a fresh kohadevbox. Now I just need to fix it...

**Comment by MagnusEnger** [comment]
I think that fixes your problem. But now I don't understand how it ever worked... Could you please confirm if it works for you now?

**Comment by jonasrog** [comment]
The status is now set in the database:
+---------+----------+
| status  | COUNT(*) |
+---------+----------+
| IN_LAST |        2 |
| IN_LEV  |        1 |
+---------+----------+

But the problem still occurs when I try to list the data from the API:
https://koha-intra/api/v1/illrequests?embed=metadata,patron,library,capabilities
Response:
{"errors":[{"message":"Internal server error.","path":"\/"}],"status":500}

When I check the plack-error.log it says:
plack-error -> [Thu Mar 21 09:46:35 2019] [error] Can't use an undefined value as an ARRAY reference at /usr/share/koha/lib/Koha/Illrequest.pm line 399.

Line 399 looks like this: @{$status_graph->{$next_action}->{prev_actions}};

**Comment by MagnusEnger** [comment]
Ah yes, that is a known problem:

Bug 22280 - The ILL module assumes every status needs a next/previous status
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=22280

>The quick solution is to change a couple of lines "around line 386 of /usr/share/koha/lib/Koha/Illrequest.pm" as I describe in the first comment on that bug.

**Comment by jonasrog** [comment]
That solved the problem.
Thanks for the help!

**Comment by MagnusEnger** [comment]
Great! Thanks for testing!
