### ISSUE TITLE
Add status Avbeställd

### ISSUE THREAD

**Issue by jonasrog** [Libriotech/koha-illbackend-libris#75]
When I go to "View ILL requests" no entries are listed in the table and the "Processing..." box is there. However, if I select anything from the dropdown where to decide how many entries to show it actually show that in the table. But the "Processing..." box is still there and I cant use the "Order by column" or the "Search" functions. All the entries are loading from the API without any errors when I tried to go directly to /api/v1/illrequests?embed=metadata,patron,library,capabilities,comments

**Comment by MagnusEnger** [comment]
Do you get any errors if you look at the (JavaScript) Console?

**Comment by jonasrog** [comment]
ill-requests.pl:586 Uncaught TypeError: Cannot read property 'name' of undefined
    at createStatus (ill-requests.pl:586)
    at jquery.dataTables.min_18.1103000.js:18
    at Object.b.fnGetData (jquery.dataTables.min_18.1103000.js:12)
    at B (jquery.dataTables.min_18.1103000.js:16)
    at Ia (jquery.dataTables.min_18.1103000.js:14)
    at mb (jquery.dataTables.min_18.1103000.js:66)
    at T (jquery.dataTables.min_18.1103000.js:30)
    at ia (jquery.dataTables.min_18.1103000.js:48)
    at HTMLTableElement.<anonymous> (jquery.dataTables.min_18.1103000.js:95)
    at Function.each (jquery-2.2.3.min_18.1103000.js:2)

**Comment by MagnusEnger** [comment]
Try the same query as last time:

```sql
SELECT status, COUNT(*) FROM illrequests GROUP BY status;
```

**Comment by jonasrog** [comment]
+-----------+----------+
| status    | COUNT(*) |
+-----------+----------+
| IN_       |        1 |
| IN_ANK    |        1 |
| IN_KANRES |        1 |
| IN_LAST   |       58 |
| IN_LEV    |      192 |
| IN_NEG    |        8 |
| IN_RESAD  |        2 |
| IN_UTEL   |        2 |
+-----------+----------+

I guess the "IN_" is causing the issue?

**Comment by MagnusEnger** [comment]
> I guess the "IN_" is causing the issue?

Yup! :-)

Can you figure out what status it should have? Look for the illrequest_id in the illrequestattributes table.

**Comment by jonasrog** [comment]
SELECT illrequest_id FROM illrequests WHERE status = 'IN_';
+---------------+
| illrequest_id |
+---------------+
|           612 |
+---------------+

SELECT value FROM illrequestattributes WHERE type = 'status' AND illrequest_id = '612';
+-------------+
| value       |
+-------------+
| Avbeställd  |
+-------------+

**Comment by jonasrog** [comment]
Cant find that in the %map array in Base.pm so I guess thats the problem

**Comment by MagnusEnger** [comment]
Spot on! Want to do a pull request? Just add IT to %map.

**Comment by jonasrog** [comment]
What code should be set when its "Avbeställd"?
And doesn't it need to be added to the status_graph just below as well?

**Comment by MagnusEnger** [comment]
True. I can do it tomorrow, if you prefer. :-)

**Comment by jonasrog** [comment]
I think that would be the best solution since im not that familiar with Libris codes etc :)
Thanks for the help once again!

**Comment by MagnusEnger** [comment]
Should be fixed now. Please test.

**Comment by jonasrog** [comment]
Works like a charm. Thanks!

**Comment by MagnusEnger** [comment]
Thanks for testing and reporting!
