### ISSUE TITLE
Log files not cleared

### ISSUE THREAD

**Issue by hanspalsson** [Libriotech/koha-illbackend-libris#76]
Log files are not purged from the folders in /etc/koha/sites. Probably easy to fix?

**Comment by MagnusEnger** [comment]
Logs are created by redirecting the output of cronjobs to files, so i prefer to delete old logs in the same place I set up the cronjobs. I have documented this here:
https://github.com/Libriotech/koha-illbackend-libris/blob/master/docs/cron.pod

Gimme a shout if that does not look OK.
