### ISSUE TITLE
Yaml file format

### ISSUE THREAD

**Issue by hanspalsson** [Libriotech/koha-illbackend-libris#94]
The example of yaml config is lacking trailing `...` . Also every entry should have a `: `. This according to YAML syntax https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

**Comment by MagnusEnger** [comment]
Agree that there is a missing colon after "libraries". 

The ... at the end of this example is just to illustrate that the list could be longer, I think:

```
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
...
```
